name: "Web Link Checker"
description: "This action traverses all of the pages of a given website and checks to see if they are valid working links"
author: "Elliot Forbes"
branding:
  icon: "link"
  color: "green"
inputs:
  url:
    description: "The root URL of the website you wish to crawl"
    required: true
    default: "https://..."
outputs:
  result:
    description: "A Report of all broken links"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.url }}
